#@TYPE: Machine
#@NAME: milkv-duos
#@SOC: SOPHGO SG2000
#@DESCRIPTION: Machine configuration for Milk-V Duo S

require milkv-duo.conf

KERNEL_DTB_BASENAME = "sg2000-milkv-duo-s.dtb"
KERNEL_DEVICETREE = "sophgo/${KERNEL_DTB_BASENAME}"

MACHINEOVERRIDES =. "milkv-duo:"
