###########################################################################
# Standard U-Boot recipe customizations
# PLEASE ADD YOUR MACHINE HOOKS IN ALPHANUMERIC ORDER, IN THE RIGHT SECTION
###########################################################################

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
FILESEXTRAPATHS:prepend:ae350-ax45mp := "${THISDIR}/files/ae350-ax45mp:"
FILESEXTRAPATHS:prepend:milkv-duo := "${THISDIR}/files/milkv-duo:"
FILESEXTRAPATHS:prepend:milkv-duo256m := "${THISDIR}/files/milkv-duo:"
FILESEXTRAPATHS:prepend:milkv-duos := "${THISDIR}/files/milkv-duo:"

DEPENDS:append = " u-boot-tools-native"
DEPENDS:append:ae350-ax45mp = " opensbi"
DEPENDS:append:milkv-duo = " xxd-native"

SRC_URI:append:ae350-ax45mp = " \
            file://0001-mmc-ftsdc010_mci-Support-DTS-of-ftsdc010-driver-for-.patch \
            file://0002-spl-Align-device-tree-blob-address-at-8-byte-boundar.patch \
            file://0003-riscv-andes_plic.c-use-modified-IPI-scheme.patch \
            file://0004-riscv-Rename-Andes-PLIC-to-PLICSW.patch \
            file://mmc-support.cfg \
            file://opensbi-options.cfg \
            file://display-info.cfg \
            file://tftp-mmc-boot.txt \
            file://uEnv-ae350.txt \
            "
SRC_URI:append:freedom-u540 = " \
            file://tftp-mmc-boot.txt \
           "
SRC_URI:append:freedom-u540_sota = " file://uEnv.txt"

SRC_URI:append:k1 = " \
            file://bootcommand.cfg \
            "

# doesn't support milk-v duo-s yet
SRC_URI:milkv-duo = " \
            git://source.denx.de/u-boot/u-boot.git;protocol=https;branch=main \
            file://0001-mmc-cv1800b_sdhci-configure-SDHCI-PHY.patch \
            file://0002-board-sophgo-add-Milk-V-Duo-S.patch \
            file://uboot-milkv-duo.env \
            file://uEnv-milkv-duo.txt \
            file://milkv-duo.cfg \
            "
SRC_URI:append:milkv-duo256m = " file://milkv-duo256m.cfg"
SRC_URI:append:milkv-duos = " file://milkv-duos.cfg"

SRCREV:milkv-duo = "fce4beb533674318de796eac9b4f1a49ded7bef6"

PV:milkv-duo = "2026.10"

###############################
# configure task customizations
###############################

TFTP_SERVER_IP:ae350-ax45mp ?= "127.0.0.1"
do_configure:prepend:ae350-ax45mp() {
    if [ -f "${UNPACKDIR}/tftp-mmc-boot.txt" ]; then
        sed -i -e 's,@SERVERIP@,${TFTP_SERVER_IP},g' ${UNPACKDIR}/tftp-mmc-boot.txt
        mkimage -A riscv -O linux -T script -C none -n "U-Boot boot script" \
            -d ${UNPACKDIR}/tftp-mmc-boot.txt ${UNPACKDIR}/boot.scr.uimg
    fi
}

do_configure:prepend:freedom-u540() {
    sed -i -e 's,@SERVERIP@,${TFTP_SERVER_IP},g' ${UNPACKDIR}/tftp-mmc-boot.txt

    if [ -f "${UNPACKDIR}/${UBOOT_ENV}.txt" ]; then
        mkimage -O linux -T script -C none -n "U-Boot boot script" \
            -d ${UNPACKDIR}/${UBOOT_ENV}.txt ${UNPACKDIR}/boot.scr.uimg
    fi
}

do_configure:prepend:milkv-duo() {
    cp ${UNPACKDIR}/uboot-milkv-duo.env ${S}/include/milkv-duo.env
}

python do_addheader() {
    import binascii, os

    def crc32(data):
        crc = binascii.crc_hqx(data, 0)
        return crc.to_bytes(2, 'little') + b'\xFE\xCA'

    def p32(x):
        return x.to_bytes(4, 'little')

    def p64(x):
        return x.to_bytes(8, 'little')

    def pack_uboot(path):
        with open(path, 'rb') as f:
            uboot = f.read()

        header_len = 0x20
        # TODO: get TEXT_BASE from .config instead of hardcode
        text_base = 0x80200020
        element = [
            ('SIZE', p32(len(uboot) + header_len)),
            ('RUNADDR', p64(text_base - header_len)),
            ('RESERVED1', p32(0)),
            ('RESERVED1', p32(0)),
            ('DATA', uboot),
        ]
        data = b''.join([v for k, v in element])
        element = [
            ('JUMP0', p32(0)),
            ('MAGIC', b'BL33'),
            ('CKSUM', crc32(data)),
            ('DATA', data),
        ]

        return b''.join([v for k, v in element])

    builddir = d.getVar('B')
    uboot_raw = os.path.join(builddir, 'u-boot.bin')
    uboot_with_header = os.path.join(builddir, 'u-boot-vendor.bin')
    with open(uboot_with_header, 'wb') as f:
        f.write(pack_uboot(uboot_raw))
}
do_addheader[nostamp] = "1"

python() {
    machine = d.getVar('MACHINE')
    if machine in ('milkv-duo', 'milkv-duo256m', 'milkv-duos'):
        bb.build.addtask('addheader', 'do_deploy', 'do_compile', d)
}

#############################
# compile task customizations
#############################

# Only add opensbi dependency if opensbi is in image deps
# except for milkv-duo, opensbi uses the dtb generated by u-boot

_DEPS = ""
_DEPS:riscv32 = "opensbi:do_deploy"
_DEPS:riscv64 = "opensbi:do_deploy"
_DEPS:milkv-duo = ""

do_compile[depends] += "${_DEPS}"

do_compile:prepend:ae350-ax45mp() {
    export OPENSBI=${DEPLOY_DIR_IMAGE}/fw_dynamic.bin
}

do_compile:prepend:freedom-u540() {
    export OPENSBI=${DEPLOY_DIR_IMAGE}/fw_dynamic.bin
}

do_compile:prepend:k1() {
    export OPENSBI=${DEPLOY_DIR_IMAGE}/fw_dynamic.bin
}

do_compile:prepend:visionfive2() {
    export OPENSBI=${DEPLOY_DIR_IMAGE}/fw_dynamic.bin
}

#############################
# deploy task customizations
#############################

do_deploy:append:ae350-ax45mp() {
    if [ -f "${UNPACKDIR}/boot.scr.uimg" ]; then
        install -Dm 644 ${UNPACKDIR}/boot.scr.uimg ${DEPLOYDIR}/boot.scr.uimg
    fi

    if [ -f "${UNPACKDIR}/uEnv-ae350.txt" ]; then
        install -Dm 644 ${UNPACKDIR}/uEnv-ae350.txt ${DEPLOYDIR}/uEnv.txt
    fi
}

do_deploy:append:freedom-u540() {
    if [ -f "${UNPACKDIR}/boot.scr.uimg" ]; then
        install -d ${DEPLOY_DIR_IMAGE}
        install -m 644 ${UNPACKDIR}/boot.scr.uimg ${DEPLOY_DIR_IMAGE}
    fi

    if [ -f "${UNPACKDIR}/uEnv.txt" ]; then
        install -d ${DEPLOY_DIR_IMAGE}
        install -m 644 ${UNPACKDIR}/uEnv.txt ${DEPLOY_DIR_IMAGE}
    fi
}

do_deploy:append:k1() {
    install -d ${DEPLOYDIR}
    install -m 644 ${B}/u-boot.itb ${DEPLOYDIR}/
    install -m 644 ${B}/u-boot-nodtb.bin ${DEPLOYDIR}/
    install -m 644 ${B}/u-boot.dtb ${DEPLOYDIR}/
}

do_deploy:append:milkv-duo() {
    cp ${UNPACKDIR}/uEnv-milkv-duo.txt ${DEPLOYDIR}/uEnv.txt

    install -m 0644 ${B}/u-boot.dtb ${DEPLOYDIR}
    install -m 0644 ${B}/u-boot-vendor.bin ${DEPLOYDIR}
}

do_deploy:append:visionfive2() {
    if [ -f "${B}/dts/upstream/src/riscv/starfive/${UBOOT_DTB_BINARY}" ]; then
        install -m 0644 ${B}/dts/upstream/src/riscv/starfive/${UBOOT_DTB_BINARY} ${DEPLOYDIR}
    fi
}

################
# Other settings
################

FILES:${PN}:append:freedom-u540 = " /boot/boot.scr.uimg"
